### ISSUE TITLE
Fibonacci numbers in C, C++, Java, Python and go

### ISSUE THREAD

**Issue by somya-kapoor** [jainaman224/Algo_Ds_Notes#1259] opened 2019-05-12 22:12 UTC
1) Finding nth Fibonacci numbers
2) printing nth Fibonacci numbers series

**Comment by AnchalJain** [comment] 2019-05-18 10:26
I can write code in python. Can I work on this issue?

**Comment by marwahmanbir** [comment] 2019-05-18 18:17
@AnchalJain since @somya-kapoor is working on it already, you can take some other issues or open a new one.

**Comment by marwahmanbir** [comment] 2019-05-18 18:19
Also, @somya-kapoor you can't start working straight after opening an issue, wait until the issue is assigned to you.
Also you have opened multiple issues at the moment, you are suggested to work on two issues at a time.

**Comment by somya-kapoor** [comment] 2019-05-18 18:39
@marwahmanbir Please assign this issue to me, I have opened this issue from the past week.

**Closed** 2019-05-25 16:41 UTC
Labels: gssoc19
