### ISSUE TITLE
Matrix Chain Multiplication in C

### ISSUE THREAD

**Issue by NVS16** [jainaman224/Algo_Ds_Notes#1794] opened 2020-03-01 08:01 UTC
I want to add matrix chain multiplication in C as it is not available, for gssoc 2020. @asha15 @singh-shreya6 @raghav-dalmia kindly assign it to me.

**Comment by singh-shreya6** [comment] 2020-03-02 21:54
@NVS16 Please don't make a PR before the issue is assigned to you.

**Comment by NVS16** [comment] 2020-03-03 05:03
Oh, sorry. My bad. I did not look. Will not happen again. :)

**Closed** 2020-03-10 14:17 UTC
Labels: GSSoC 20, easy
