### ISSUE TITLE
0-1 Knapsack Problem in python (GSSoC Participant)

### ISSUE THREAD

**Issue by joel-razor1** [jainaman224/Algo_Ds_Notes#486] opened 2019-03-04 06:36 UTC
I've noticed that 0-1 Knapsack Program is available in c++ and java only. I would like to work on this problem.

**Comment by souka1** [comment] 2019-03-04 13:00
I would like to work on this problem

**Comment by diptinayan** [comment] 2019-03-04 16:52
I am highly interested to work on this problem.

**Comment by Jaseemck** [comment] 2019-03-05 14:52
I can code the program in python and c. I have done it in c++ and quite strong in its concept. I can close this issue within the deadline. So please assign me on this @jainaman224 .

**Comment by shadow989** [comment] 2019-03-06 04:17
I'm interested in this issue and can do this within the time provided .I have worked on this algorithm in c language and can do it in python for sure..

**Comment by jainaman224** [comment] 2019-03-06 05:09
@Jaseemck Go ahead if it is not implemented in any of those language.

**Comment by jainaman224** [comment] 2019-03-06 05:09
@shadow989 Please have a look at other issues.

**Comment by Karna98** [comment] 2019-03-23 20:02
is this issue open? I want to work on it.

**Comment by jainaman224** [comment] 2019-03-24 06:34
@Karna98 Please specify the language.

**Comment by Karna98** [comment] 2019-03-24 08:58
@jainaman224 Renaming of the issue is required as it has been already implemented.
or Close the issue.

**Comment by jainaman224** [comment] 2019-03-24 17:16
Ok

**Closed by jainaman224** 2019-03-24 17:16 UTC
Labels: gssoc19
