### ISSUE TITLE
Reverse singly linked list

### ISSUE THREAD

**Issue by abhishekgupta368** [jainaman224/Algo_Ds_Notes#1652] opened 2020-02-29 07:12 UTC
The reverse of a single linked list is missing, can you please assign me that

**Comment by asha15** [comment] 2020-02-29 08:54
@abhishekgupta368 Can you specify the languages you want to work with?

**Comment by abhishekgupta368** [comment] 2020-02-29 09:27
I will do in python

**Comment by j-shreya** [comment] 2020-02-29 14:28
I can implement this in java. Pls assign this to me

**Comment by asha15** [comment] 2020-02-29 14:32
@abhishekgupta368 Go for it.
@j-shreya Please create a new issue for it

**Comment by abhishekgupta368** [comment] 2020-02-29 14:33
thank you

**Comment by abhishekgupta368** [comment] 2020-02-29 14:35
I have to create a new issue by the same name?

**Comment by asha15** [comment] 2020-02-29 14:43
@abhishekgupta368 no. @j-shreya like to implement this algo using java,that's why i asked her to create a new issue for it. you don't need to create a new one, start to work on this.
All the best

**Comment by abhishekgupta368** [comment] 2020-02-29 14:43
thank you

**Comment by Jahnavi-Jonnalagadda** [comment] 2020-03-01 01:28
Hi There! I would like to work on this issue in Python. Could you please assign this to me @asha15

**Comment by ritish099** [comment] 2020-03-01 07:53
As a participant of GSSoC, I would like to work on this. Please assign this task to me. I can implement it in c,c++;

**Comment by asha15** [comment] 2020-03-01 18:41
@Jahnavi-Jonnalagadda  please create a new issue for it
@ritish099  the issue is already taken

**Comment by Riyagoel2** [comment] 2020-03-08 13:31
Hi I would like to work on it in Java. Please assign it to me @asha15

**Comment by thesrijande** [comment] 2020-03-31 14:21
assign me

**Closed** 2020-05-01 11:19 UTC
Labels: GSSoC20, easy
